# Generated by Django 3.0.2 on 2020-01-30 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CahierTexte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_cours', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_class', models.CharField(max_length=50)),
                ('login_class', models.CharField(max_length=50)),
                ('password_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.CharField(max_length=50)),
                ('duree', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_eleve', models.CharField(max_length=50)),
                ('prenom_eleve', models.CharField(max_length=50)),
                ('grade_eleve', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fk_id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=30)),
                ('fk_id_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Cours')),
                ('fk_id_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='PresAbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Cours')),
                ('fk_id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Classe')),
                ('fk_id_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Prof')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='fk_id_elev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Eleve'),
        ),
    ]
